COMMENT =	drop-in replacement for node fs module

DIST_TUPLE =	github isaacs node-graceful-fs v4.2.11 .
REVISION =	0

CATEGORIES =	devel

MAINTAINER =	Fabien Romano <fabien@openbsd.org>

# BlueOak
PERMIT_PACKAGE =	Yes

MODULES =		devel/npm
MODNPM_MODS_SKIP =	graceful-fs
MODNPM_INSTALL =	graceful-fs

.include "modules.npm.inc"

.include <bsd.port.mk>
