#!/bin/sh

DATASIZE="8388608" # 8G

xm_log() {
	echo -n "$@\nDo you want to run Beyond All Reason anyway?" | \
		${X11BASE}/bin/xmessage -file - -center -buttons yes:0,no:1 -default no
}

# bump limit
if [ $(ulimit -Sd) -lt ${DATASIZE} ]; then
	ulimit -Sd ${DATASIZE} || \
		xm_log "Cannot increase datasize-cur to at least ${DATASIZE}
(If you don't increase these limits, spring might fail to work properly.)"
		[ $? -eq 0 ] || exit
fi

# pre-create folder for unveil
# unveil.bar-lobby doesn't handle XDG custom path, use fixed path
# XXX may not be convenient but we lack electron support to unveil XDG stuff
[ -d "${HOME}/.local/state/BeyondAllReason" ] || \
	mkdir -p "${HOME}/.local/state/BeyondAllReason"
[ -d "${HOME}/.local/share/BeyondAllReason/assets" ] || \
	mkdir -p "${HOME}/.local/share/BeyondAllReason/assets"

#start
BAR_STATE_PATH="${HOME}/.local/state/BeyondAllReason" \
BAR_ASSETS_PATH="${HOME}/.local/share/BeyondAllReason/assets" \
ELECTRON_IS_DEV=0 \
ELECTRON_FORCE_IS_PACKAGED=1 \
NODE_ENV=production \
ELECTRON_APP_NAME="${MODELECTRON_APP_NAME}" \
ELECTRON_UNVEIL="${MODELECTRON_UNVEIL_FILE}" \
exec ${TRUEPREFIX}/${ELECTRON_WRAPPER} \
	--app="${TRUEPREFIX}/${MODELECTRON_DIST_T}.asar" $@
