     SUBDIR =
     SUBDIR += app-builder
     SUBDIR += ast-grep
     SUBDIR += berry
     SUBDIR += esbuild
     SUBDIR += gclient
     SUBDIR += gn
     SUBDIR += go-bindata
     SUBDIR += node-graceful-fs
     SUBDIR += npm
     SUBDIR += oxc-apps
     SUBDIR += oxc-node
     SUBDIR += parcel-watcher
     SUBDIR += pnpm
     SUBDIR += py-dbusmock
     SUBDIR += rolldown
     SUBDIR += rollup
     SUBDIR += yarn

.include <bsd.port.subdir.mk>
