     SUBDIR =
     SUBDIR += app-builder
     SUBDIR += esbuild
     SUBDIR += gclient
     SUBDIR += gn
     SUBDIR += parcel-watcher
     SUBDIR += pnpm
     SUBDIR += py-dbusmock
     SUBDIR += yarn

.include <bsd.port.subdir.mk>
