MODGO_MODULES+=	\
	github.com/!microsoft/go-winio		 v0.6.2 \
	github.com/go-json-experiment/json	 v0.0.0-20260214004413-d219187c3433 \
	github.com/google/go-cmp		 v0.7.0 \
	github.com/klauspost/cpuid/v2		 v2.2.10 \
	github.com/mackerelio/go-osstat		 v0.2.7 \
	github.com/matryer/moq			 v0.7.1 \
	github.com/peter-evans/patience		 v0.3.0 \
	github.com/pmezard/go-difflib		 v1.0.0 \
	github.com/sirupsen/logrus		 v1.9.3 \
	github.com/yuin/goldmark		 v1.4.13 \
	github.com/zeebo/assert			 v1.3.0 \
	github.com/zeebo/xxh3			 v1.1.0 \
	golang.org/x/mod			 v0.35.0 \
	golang.org/x/net			 v0.53.0 \
	golang.org/x/sync			 v0.20.0 \
	golang.org/x/sys			 v0.43.0 \
	golang.org/x/telemetry			 v0.0.0-20260409153401-be6f6cb8b1fa \
	golang.org/x/term			 v0.42.0 \
	golang.org/x/text			 v0.36.0 \
	golang.org/x/tools			 v0.44.0 \
	gotest.tools/v3				 v3.5.2

MODGO_MODFILES+=	\
	github.com/google/go-cmp	 v0.5.9 \
	github.com/google/go-cmp	 v0.6.0 \
	golang.org/x/mod		 v0.12.0 \
	golang.org/x/mod		 v0.23.0 \
	golang.org/x/mod		 v0.34.0 \
	golang.org/x/sync		 v0.11.0 \
	golang.org/x/sys		 v0.10.0 \
	golang.org/x/sys		 v0.12.0 \
	golang.org/x/sys		 v0.30.0 \
	golang.org/x/sys		 v0.42.0 \
	golang.org/x/tools		 v0.11.0 \
	golang.org/x/tools		 v0.13.0 \
	golang.org/x/tools		 v0.30.0 \
	golang.org/x/tools		 v0.43.0

MODGO_MODULES+=	\
	github.com/golangci/plugin-module-register	 v0.1.2 \
	github.com/google/go-cmp			 v0.6.0 \
	github.com/yuin/goldmark			 v1.4.13 \
	golang.org/x/mod				 v0.35.0 \
	golang.org/x/net				 v0.53.0 \
	golang.org/x/sync				 v0.20.0 \
	golang.org/x/sys				 v0.43.0 \
	golang.org/x/telemetry				 v0.0.0-20260409153401-be6f6cb8b1fa \
	golang.org/x/tools				 v0.44.0 \
	gotest.tools/v3					 v3.5.2

MODGO_MODFILES+=	\
	github.com/google/go-cmp	 v0.5.9 \
	golang.org/x/mod		 v0.12.0 \
	golang.org/x/sys		 v0.12.0 \
	golang.org/x/tools		 v0.13.0 \
	golang.org/x/tools		 v0.32.0 \
	golang.org/x/tools		 v0.43.0

